### ISSUE TITLE
conda-package-handling fails to build with Python 3.11: AttributeError: module 'configparser' has no attribute 'SafeConfigParser'

### ISSUE THREAD

**Issue by opoplawski** [conda/conda-package-handling#85]
See also https://bugzilla.redhat.com/show_bug.cgi?id=2026925

python-conda-package-handling fails to build with Python 3.11.0a2.
```
Traceback (most recent call last):
  File "/builddir/build/BUILD/conda-package-handling-1.7.3/setup.py", line 27,
in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/conda-package-handling-1.7.3/versioneer.py", line
1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/conda-package-handling-1.7.3/versioneer.py", line
1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/conda-package-handling-1.7.3/versioneer.py", line
342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did
you mean: 'RawConfigParser'?
```
Removed from the configparser module: the SafeConfigParser class, the filename
property of the ParsingError class, the readfp() method of the ConfigParser
class, deprecated since Python 3.2. (Contributed by Hugo van Kemenade in
bpo-45173.)

https://bugs.python.org/issue45173
https://docs.python.org/3.11/whatsnew/3.11.html

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.11/fedora-rawhide-x86_64/02990019-python-conda-package-handling/

For all our attempts to build python-conda-package-handling with Python 3.11,
see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.11/package/python-conda-package-handling/

Testing and mass rebuild of packages is happening in copr. You can follow these
instructions to test locally in mock if your package builds with Python 3.11:
https://copr.fedorainfracloud.org/coprs/g/python/python3.11/
